# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class DataStreamServiceStub(object):
    """The new service name
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFeatures = channel.unary_unary(
                '/DataStreamService/SendFeatures',
                request_serializer=data__pb2.FeatureRequest.SerializeToString,
                response_deserializer=data__pb2.FeatureResponse.FromString,
                )


class DataStreamServiceServicer(object):
    """The new service name
    """

    def SendFeatures(self, request, context):
        """The new function name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFeatures,
                    request_deserializer=data__pb2.FeatureRequest.FromString,
                    response_serializer=data__pb2.FeatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataStreamService(object):
    """The new service name
    """

    @staticmethod
    def SendFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataStreamService/SendFeatures',
            data__pb2.FeatureRequest.SerializeToString,
            data__pb2.FeatureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
