# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"5\n\x0e\x46\x65\x61tureRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"3\n\x0f\x46\x65\x61tureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2H\n\x11\x44\x61taStreamService\x12\x33\n\x0cSendFeatures\x12\x0f.FeatureRequest\x1a\x10.FeatureResponse\"\x00\x62\x06proto3')



_FEATUREREQUEST = DESCRIPTOR.message_types_by_name['FeatureRequest']
_FEATURERESPONSE = DESCRIPTOR.message_types_by_name['FeatureResponse']
FeatureRequest = _reflection.GeneratedProtocolMessageType('FeatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:FeatureRequest)
  })
_sym_db.RegisterMessage(FeatureRequest)

FeatureResponse = _reflection.GeneratedProtocolMessageType('FeatureResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEATURERESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:FeatureResponse)
  })
_sym_db.RegisterMessage(FeatureResponse)

_DATASTREAMSERVICE = DESCRIPTOR.services_by_name['DataStreamService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEATUREREQUEST._serialized_start=14
  _FEATUREREQUEST._serialized_end=67
  _FEATURERESPONSE._serialized_start=69
  _FEATURERESPONSE._serialized_end=120
  _DATASTREAMSERVICE._serialized_start=122
  _DATASTREAMSERVICE._serialized_end=194
# @@protoc_insertion_point(module_scope)
